version: "3.3"
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=shoppingify
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - db