export const SEQUELIZE = 'SEQUELIZE';
export const ITEMS_REPOSITORY = 'ITEMS_REPOSITORY';
export const CATEGORIES_REPOSITORY = 'CATEGORIES_REPOSITORY';
export const SHOPPING_LIST_REPOSITORY = 'SHOPPING_LIST_REPOSITORY';
